#!/usr/bin/env python3

import sys
from electrum_ganja import Network
from electrum_ganja.util import json_encode, print_msg
from electrum_ganja import ganja

try:
    addr = sys.argv[1]
except Exception:
    print("usage: get_history <ganjacoin_address>")
    sys.exit(1)

n = Network()
n.start()
_hash = ganja.address_to_scripthash(addr)
h = n.synchronous_get(('blockchain.address.get_history',[_hash]))
print_msg(json_encode(h))
